#!/bin/bash

# Written by Bong McPuffin
# Tested last on Jan 2nd, 2019

if [[ "$(cat /tmp/.conkystate)" = "above" ]]; then
    STATE="below"
    REMOVE="above"
    sed -i 's/above/below/g' /home/CHANGEUSER/.conky/GameMonitor/conkyrc
else
    STATE="above"
    REMOVE="below"
    sed -i 's/below/above/g' /home/CHANGEUSER/.conky/GameMonitor/conkyrc
fi
    echo $STATE > /tmp/.conkystate

for t in Todo-Conky QuodLibet-Conky QuodLibet-Conky-Cover; do
    wmctrl -F -r $t -b remove,$REMOVE
    wmctrl -F -r $t -b add,$STATE
done
